 # List of big joints (according to DAS66)
L_Big_Joints_66 = ['Pijn_schouder L', 
 'Pijn_schouder R', 
 'Pijn_Elleboog links',
 'Pijn_elleboog rechts', 
 'Pijn_heup links', 
 'Pijn_heup rechts', 
 'Pijn_knie links', 
 'Pijn_knie rechts', 
 'Zwelling_schouder L', 
 'Zwelling_schouder R',
 'Zwelling_Elleboog links', 
 'Zwelling_elleboog rechts',
 'Zwelling_heup links',
 'Zwelling_heup rechts',
 'Zwelling_knie links', 
 'Zwelling_knie rechts',
 'Pijn_onderste spronggewricht links', 
 'Pijn_onderste spronggewricht rechts', 
 'Pijn_bovenste spronggewicht links', 
 'Pijn_bovenste spronggewricht rechts',
 'Zwelling_onderste spronggewricht links', 
 'Zwelling_onderste spronggewricht rechts', 
 'Zwelling_bovenste spronggewicht links', 
 'Zwelling_bovenste spronggewricht rechts',
 'Zwelling_cervical spine', 
 'Pijn_cervical spine', 
 'Pijn_sacro-ileacaal gewricht links', 
 'Pijn_sacro-ileacaal gewricht rechts',
                 ] 